name: 'schicht-planer-lit-nofront'

services:
  # Backend setup

  planner-logic-gate:
    container_name: planner-logic-gate
    build:
      context: ../../
      dockerfile: planner-backend/modules/logicGate/Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    networks:
      - planner-network

  planner-scheduler:
    depends_on:
      - planner-mariadb
    container_name: planner-scheduler
    build:
      context: ../../
      dockerfile: planner-backend/modules/scheduler/Dockerfile
    ports:
      - "8081:8081"
    env_file:
      - .env
    restart: always
    networks:
      - planner-network

  planner-auth:
    depends_on:
      - planner-mariadb
    container_name: planner-auth
    build:
      context: ../../
      dockerfile: planner-backend/modules/auth/Dockerfile
    ports:
      - "8082:8082"
    env_file:
      - .env
    restart: always
    networks:
      - planner-network
      
  planner-stats:
    depends_on:
      - planner-mariadb
    container_name: planner-stats
    build:
      context: ../../
      dockerfile: planner-backend/modules/statistics/Dockerfile
    ports:
      - "8083:8083"
    env_file:
      - .env
    restart: always
    networks:
      - planner-network

  # Database setup
  planner-mariadb:
    image: mariadb:latest
    container_name: planner-mariadb
    ports:
      - "3306:3306"
    expose:
      - "3306"
    networks:
      - planner-network
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: planner
      MARIADB_USER: planner
      MARIADB_PASSWORD: root

# Networks
networks:
  planner-network:
    driver: bridge