
name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'planner-backend/**'
      - 'planner-frontend/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-back:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          echo "Building the backend..."
          cd planner-backend
          chmod +x mvnw
          ./mvnw clean package

      - name: Build container
        run: |
          echo "Building the container..."
          docker compose -f schichtconfig/docker/docker-compose.yml build --no-cache

      - name: Run container
        run: |
          echo "Running the container..."
          docker compose -f schichtconfig/docker/docker-compose.yml down || true
          docker compose -f schichtconfig/docker/docker-compose.yml up -d
           
#  build-front: